 
kind: Service
apiVersion: v1
metadata:
  name:  fluentd-elasticsearch-service
  namespace: kube-system
spec:
  selector:
    app: fluentd-elasticsearch
  type:  NodePort
  ports:
  - name:  fluentd-elasticsearch
    port:  80
    targetPort:  9200
    nodePort:  30010
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-elasticsearch
  namespace: kube-system
  labels:
    k8s-app: fluentd-logging
spec:
  selector:
    matchLabels:
      name: fluentd-elasticsearch
  template:
    metadata:
      labels:
        name: fluentd-elasticsearch
        app: fluentd-elasticsearch
    spec:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
      containers:
        - name: fluentd
          image: fluent/fluentd-kubernetes-daemonset:v1.16.2-debian-elasticsearch7-1.0
          env:
            - name: FLUENT_ELASTICSEARCH_HOST # dựng elastichsearch để nó push log tới service tập trung log này
              value: "elasticsearch.logging.svc.cluster.local"  # đổi theo tên service Elasticsearch của bạn
            - name: FLUENT_ELASTICSEARCH_PORT
              value: "9200"
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers