apiVersion: batch/v1
kind: Job #dùng để chạy 1 lần như migrate db, import csv
metadata:
  name: db-backup-job
spec:
  ttlSecondsAfterFinished: 10
  template:
    spec:
      containers:
      - name: backup
        image: busybox
        command: ["/bin/sh", "-c"]
        args:
          - "echo 'Backing up database...' && sleep 20  "
      restartPolicy: Never
